apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.3.0
        profile:
            VendorType: partner
            version: v1.1
        chart-uri: https://github.com/ansvu/samplechart2/releases/download/samplechart-0.1.2/samplechart-0.1.2.tgz
        digest: sha256:4abe3a57dcc5865e006b8165507a06b4f165b282a53afb3060a1ff0733c4f2dd
        digests:
            chart: sha256:4abe3a57dcc5865e006b8165507a06b4f165b282a53afb3060a1ff0733c4f2dd
            package: 22e56280264b02562e7c82c6a224bad6386e8bdd4bc7c7504ab8f92bbb46bc66
        lastCertifiedTimestamp: "2021-12-07T17:11:14.072258-06:00"
        certifiedOpenShiftVersions: 4.7.0
    chart:
        name: samplechart
        home: ""
        sources: []
        version: 0.1.2
        description: A Helm chart for Kubernetes
        keywords: []
        maintainers: []
        icon: https://www.example.com/chart-icon.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1-42
        deprecated: false
        annotations:
            charts.openshift.io/archs: x86_64
            charts.openshift.io/name: RedHat Test
            charts.openshift.io/provider: RedHat
            charts.openshift.io/supportURL: https://github.com/dperaza4dustbit/helm-chart
            charts.openshift.io/testedOpenShiftVersion: 4.7.0
        kubeversion: '>=1.20.0'
        dependencies: []
        type: application
    chart-overrides: ""
results:
  - check: v1.0/contains-values
    type: Mandatory
    outcome: PASS
    reason: Values file exist
  - check: v1.0/contains-values-schema
    type: Mandatory
    outcome: PASS
    reason: Values schema file exist
  - check: v1.0/helm-lint
    type: Mandatory
    outcome: PASS
    reason: Helm lint successful
  - check: v1.0/not-contain-csi-objects
    type: Mandatory
    outcome: PASS
    reason: CSI objects do not exist
  - check: v1.0/images-are-certified
    type: Mandatory
    outcome: PASS
    reason: 'Image is Red Hat certified : registry.access.redhat.com/ubi8/nginx-118:1-42'
  - check: v1.0/has-readme
    type: Mandatory
    outcome: PASS
    reason: Chart has a README
  - check: v1.0/is-helm-v3
    type: Mandatory
    outcome: PASS
    reason: API version is V2, used in Helm 3
  - check: v1.0/contains-test
    type: Mandatory
    outcome: PASS
    reason: Chart test files exist
  - check: v1.0/chart-testing
    type: Mandatory
    outcome: PASS
    reason: Chart tests have passed
  - check: v1.0/required-annotations-present
    type: Mandatory
    outcome: PASS
    reason: All required annotations present
  - check: v1.0/has-kubeversion
    type: Mandatory
    outcome: PASS
    reason: Kubernetes version specified
  - check: v1.0/not-contains-crds
    type: Mandatory
    outcome: PASS
    reason: Chart does not contain CRDs
